spring:
  application:
    name: gateway-server
  #cloud:
    #config:
      #uri: http://localhost:8071
      ##fail-fast: true
      #retry:
        #max-attempts: 20
        #max-interval: 15000
        #initial-interval: 10000
  config:
    import: 'optional:configserver:http://localhost:8071'

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

