eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/
    instance:
        preferIpAddress: true
management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: '*'
server:
    port: 8072
spring:
    application:
        name: gateway-server
    cloud:
        bus:
            enabled: true
            refresh:
                enabled: true
        gateway:
            discovery:
                locator:
                    enabled: true
                    lowerCaseServiceId: true
        loadbalancer:
            ribbon:
                enabled: false
        stream:
            kafka:
                binder:
                    brokers: localhost:2181,127.0.1:2181
                    zkNodes: localhost:9092,127.0.0.1:9092
    config:
        import: optional:configserver:http://localhost:8071
